---
- hosts: all
  become: yes
  tasks:
  - name: install webserver
    package:
      name: "{{ package_name }}"
      state: present
  - name:  update package
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
  
  - name: "install ftp"
    yum:
      name: ftp
    when: ansible_os_family == "RedHat"
  
  - name: "install utilities"
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - git
    - tree
    - nano
  
  
# ansible-playbook -i "inventory/hosts" web.yaml
  